<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kbs</string>
	</array>
	<key>name</key>
	<string>KBS</string>
	<key>patterns</key>

<array>
		<dict>
			<key>match</key>
			<string>\b(CxComp|CxDecl|CxFlexModel|CxParaGroup|CxArbit|CxKB|CxPref|CxArbitMod|CxAccNum|CxArbModNum|CxFloat|CxEnum|CxCompPara|CxContainerPara|CxNum|CxConsGroup|CxRule|CxMExp|CxExp|CxSQLProps|CxDBProps|CxActAddContElem|CxDDCmp|CxFuncExp|CxArbitMulti|CxMultiEnum|CxFunc)\b</string>
			<key>name</key>
			<string>keyword.control.text.kbs</string>
		</dict> 
		<dict>
			<key>match</key>
			<string>(\*|\b/\b|%|\+|-|\*\*|\#|\@|\^|\|=|\?|&amp;)</string>
			<key>name</key>
			<string>keyword.operator.text.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\[|\]|{|})</string>
			<key>name</key>
			<string>keyword.operator.text.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NMPostingEnable|NMPostingConstraintFiltering)\b</string>
			<key>name</key>
			<string>variable.parameter.text.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(noRollUp|float|noAutoAssign|noRecurse|virtual|delayedEval|mustPreset|stickyPreset|defineHide)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?(f|F|L)?\b</string>
			<key>name</key>
			<string>constant.numeric.text.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CREATE|(NOT| )?MEMBER|ASSIGNED)\b</string>
			<key>name</key>
			<string>comment.other.kbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.text.kbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>["|\\"]</string>
			<key>end</key>
			<string>["|\\"]</string>
			<key>name</key>
			<string>string.quoted.double.text.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A]|[P]|[R]|[S])\b</string>
			<key>name</key>
			<string>storage.type.text.kbs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.text.kbs</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.kbs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.text.kbs</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.name.tag.kbs</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.other.attribute.kbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z_]+[A-Za-z_0-9]*( as ([A-Z]+[A-Za-z_0-9]*)))\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string> (?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+)(=| =)</string>
			<key>name</key>
			<string>variable.parameter.text.kbs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.kbs</string>
	<key>uuid</key>
	<string>f87d9ac8-6cf4-4881-9dbd-b9c766c89ad0</string>
</dict>
</plist>
