<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kbs</string>
	</array>
	<key>name</key>
	<string>Kbs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(CxComp|CxDecl|CxFlexModel|CxParaGroup|CxArbit|CxKB|CxPref|CxArbitMod|CxAccNum|CxArbModNum|CxFloat|CxEnum|CxCompPara|CxContainerPara|CxNum|CxConsGroup|CxRule|CxMExp|CxExp|CxSQLProps|CxDBProps|CxActAddContElem|CxDDCmp|CxFuncExp|CxArbitMulti|CxMultiEnum|CxFunc)\b</string>
			<key>name</key>
			<string>keyword.control.source.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*|\b/\b|%|\+|-|\*\*|\#|\@|\^|\|=)</string>
			<key>name</key>
			<string>keyword.operator.source.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\[|\]|{|})</string>
			<key>name</key>
			<string>keyword.operator.source.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NMPostingEnable|NMPostingConstraintFiltering)\b</string>
			<key>name</key>
			<string>entity.name.tag.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(noRollUp|float|noAutoAssign|noRecurse|virtual|delayedEval)\b</string>
			<key>name</key>
			<string>entity.name.attribute.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?(f|F|L)?\b</string>
			<key>name</key>
			<string>constant.numeric.source.kbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.source.kbs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.kbs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A]|[P]|[R]|[S])\b</string>
			<key>name</key>
			<string>storage.type.source.kbs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.kbs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.kbs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.kbs</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.name.tag.kbs</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.name.attribute.kbs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z_]+[A-Za-z_0-9]*( as ([A-Z]+[A-Za-z_0-9]*)))\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string> (?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+)=|(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+) =|\?</string>
			<key>name</key>
			<string>variable.parameter.source.kbs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kbs</string>
	<key>uuid</key>
	<string>40d7173c-d213-4009-938e-5249ec75849d</string>
</dict>
</plist>
